version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: fastapi-app
      MONGO_INITDB_ROOT_PASSWORD: not-a-real-password
  api:
    build:
      context: .
      dockerfile: src/per_object_permissions/docker/mongodb/Dockerfile
    ports:
      - 8008:8008
    depends_on:
      - mongo
  test:
    build:
      context: .
      dockerfile: tests/integration/Dockerfile
    depends_on:
      - api
