version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/not-a-real-password
    ports:
      - 7474:7474
      - 7687:7687
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
  api:
    build:
      context: .
      dockerfile: src/per_object_permissions/docker/neo4j/Dockerfile
    ports:
      - 8008:8008
    depends_on:
      neo4j:
        condition: service_healthy
