version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/per_object_permissions/docker/in_memory/Dockerfile
    ports:
      - 8008:8008
  test:
    build:
      context: .
      dockerfile: tests/integration/Dockerfile
    environment:
      - BACKEND_NAME=in-memory
    volumes:
      - ./test_output/:/test_output
    depends_on:
      - api
